version: '3'
services:
  app:
    image: orderdetails:LATEST
    restart: on-failure
    build:
      context: .
      args:
        JAR_FILE: target/orderdetails-0.0.1-SNAPSHOT.jar
    ports:
      - 9080:9080
    environment:
      - MYSQL_ROOT_HOST=jdbc:mysql://docker-mysql:3306/practice
    depends_on:
      - db
    networks:
      - mynetwork
  db:
    image: mysql:latest
    volumes:
      - mysql:/data/db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password

networks:
  {'mynetwork'}
volumes:
  mysql:



