version: '3'
services:
  docker-mysql:
    restart: always
    container_name: docker-mysql
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: practice
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "6033:3306"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=root--execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 5
  app:
    image: orderdetails:LATEST
    restart: on-failure
    build:
      context: .
      args:
        JAR_FILE: target/orderdetails-0.0.1-SNAPSHOT.jar
    ports:
      - 9080:9080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://docker-mysql:3306/practice?autoReconnect=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      WAIT_HOSTS: mysql:3306
    depends_on:
      - docker-mysql

volumes:

  sql:



