version: '3.7'
services:
  docker-mysql:
    restart: always
    container_name: docker-mysql
    image: mysql
    environment:
      MYSQL_DATABASE: practice
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
    volumes:
       - ./sql:/docker-entrypoint-initdb.d
    ports:
      - "6033:3306"
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=root--execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 3
  orderdetails:
    restart: on-failure
    build: ./
    expose:
      - "10222"
    ports:
      - 10222:9090
    environment:
      WAIT_HOST: mysql:3306
    depends_on:
      - docker-mysql

